<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
  	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  	<NoWarn>$(NoWarn);1591</NoWarn> <!-- Отключает предупреждения об отсутствии документации для всех публичных членов -->
	<NoWarn>$(NoWarn);1573</NoWarn> <!-- Отключает предупреждения об отсутствии совпадающего тега param. Например, это относится к this ILogger (метод расширения), ну а где-то я и правда забыл -->

	<PackageOutputPath>..\nugets</PackageOutputPath>
  	<PackageVersion>1.1.0</PackageVersion>
  </PropertyGroup>	
	
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
  </ItemGroup>

</Project>
