# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'   # ВАЖНО, кстати
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"] # Сервер prometheus
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: 'WebApi'
    scrape_interval: 5s # Каждые 5 секунд мониторить метрики
    #scheme: https # ВАЖНО, чтобы в приложении не было UseHttpsRedirection
    static_configs:
      - targets: ["host.docker.internal:8080"]  # Моё приложение
    basic_auth: # Авторизация
      username: 'test'
      password: '123'
      
  - job_name: 'EmailSender'
    scrape_interval: 5s # Каждые 5 секунд мониторить метрики
    #scheme: https
    static_configs:
      - targets: ["host.docker.internal:8083"]  # Моё приложение с протоколом HTTP1
    basic_auth: # Авторизация
      username: 'test'
      password: '123'